name: PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: pytest -h
